import React, { useEffect, useState } from 'react';
import { FileBarChart, Download } from 'lucide-react';
import ProgressBar from '../components/ProgressBar';

const ReportsPage: React.FC = () => {
  const [showModal, setShowModal] = useState(false);
  const [report, setReport] = useState<any>(null);

  useEffect(() => {
    document.title = "Reports | Space360";
  }, []);

  const handleGenerate = () => {
    setShowModal(false);
    setReport({
      siteName: 'Downtown Highrise',
      dateRange: 'Oct 01, 2023 - Oct 15, 2023',
      overallProgress: 45,
      locations: [
        {
          name: 'Level 1 Center',
          beforeThumb: 'https://pannellum.org/images/alma.jpg',
          afterThumb: 'https://pannellum.org/images/cerro-toco-0.jpg',
          summary: 'Significant structural progress with concrete pillars fully poured.'
        },
        {
          name: 'Level 2 North',
          beforeThumb: 'https://pannellum.org/images/bma-0.jpg',
          afterThumb: 'https://pannellum.org/images/jfk.jpg',
          summary: 'HVAC rough-in initiated in the northern corridor.'
        }
      ]
    });
  };

  const exportPDF = () => {
    window.print();
  };

  return (
    <div className="space-y-6">
      {/* Hide this top section during print */}
      <div className="print:hidden">
        <div className="flex justify-between items-center mb-6">
          <h2 className="text-2xl font-bold text-gray-800">Progress Reports</h2>
          <button onClick={() => setShowModal(true)} className="btn-primary flex items-center shadow-md">
            <FileBarChart className="w-4 h-4 mr-2" />
            Generate Report
          </button>
        </div>

        <div className="card overflow-hidden p-0 mb-6 shadow-sm border border-gray-200">
          <table className="w-full text-left text-sm text-gray-600">
            <thead className="bg-gray-100 text-gray-700 uppercase text-xs tracking-wider border-b border-gray-200">
              <tr>
                <th className="px-6 py-4 font-bold">Site</th>
                <th className="px-6 py-4 font-bold">Date Range</th>
                <th className="px-6 py-4 font-bold">Generated By</th>
                <th className="px-6 py-4 font-bold text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              <tr className="hover:bg-blue-50 transition-colors">
                <td className="px-6 py-4 font-bold text-gray-900">Westside Mall</td>
                <td className="px-6 py-4 font-medium text-gray-600">Sep 1, 2023 - Sep 30, 2023</td>
                <td className="px-6 py-4">Admin User</td>
                <td className="px-6 py-4 text-right">
                  <button className="text-brand-600 hover:text-brand-800 font-bold text-xs uppercase tracking-wider bg-brand-50 px-3 py-1.5 rounded border border-brand-100 hover:bg-brand-100 transition-colors">Download PDF</button>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      {showModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-60 backdrop-blur-sm print:hidden">
          <div className="bg-white rounded-2xl shadow-2xl p-8 w-full max-w-md animate-fade-in">
            <div className="flex items-center mb-6">
              <FileBarChart className="w-6 h-6 text-brand-600 mr-2" />
              <h3 className="text-2xl font-bold text-gray-900">Generate Report</h3>
            </div>
            
            <div className="space-y-5">
              <div>
                <label className="block text-sm font-bold text-gray-700 mb-1.5">Site</label>
                <select className="input font-medium bg-gray-50"><option>Downtown Highrise</option></select>
              </div>
              <div className="flex space-x-4">
                <div className="flex-1">
                  <label className="block text-sm font-bold text-gray-700 mb-1.5">From</label>
                  <input type="date" className="input font-medium bg-gray-50" />
                </div>
                <div className="flex-1">
                  <label className="block text-sm font-bold text-gray-700 mb-1.5">To</label>
                  <input type="date" className="input font-medium bg-gray-50" />
                </div>
              </div>
              <div>
                <label className="block text-sm font-bold text-gray-700 mb-2">Locations</label>
                <div className="space-y-2 border border-gray-200 bg-gray-50 rounded-lg p-3 h-36 overflow-y-auto shadow-inner">
                  <label className="flex items-center space-x-3 p-2 hover:bg-white rounded border border-transparent hover:border-gray-200 transition-colors cursor-pointer">
                    <input type="checkbox" defaultChecked className="rounded text-brand-600 w-4 h-4 focus:ring-brand-500" />
                    <span className="font-medium text-gray-800">Level 1 Center</span>
                  </label>
                  <label className="flex items-center space-x-3 p-2 hover:bg-white rounded border border-transparent hover:border-gray-200 transition-colors cursor-pointer">
                    <input type="checkbox" defaultChecked className="rounded text-brand-600 w-4 h-4 focus:ring-brand-500" />
                    <span className="font-medium text-gray-800">Level 2 North</span>
                  </label>
                </div>
              </div>
            </div>
            <div className="flex justify-end space-x-3 mt-8 pt-4 border-t border-gray-100">
              <button onClick={() => setShowModal(false)} className="px-5 py-2.5 font-bold text-gray-600 hover:bg-gray-100 rounded-lg transition-colors">Cancel</button>
              <button onClick={handleGenerate} className="btn-primary px-6 py-2.5 shadow-md">Generate PDF Report</button>
            </div>
          </div>
        </div>
      )}

      {/* Report Preview - Visible on screen and in print */}
      {report && (
        <div className="card max-w-4xl mx-auto shadow-2xl print:shadow-none print:m-0 print:p-0 print:w-full print:max-w-none border border-gray-200 bg-white">
          <div className="flex justify-between items-end border-b-2 border-gray-200 pb-6 mb-8">
            <div>
              <h1 className="text-4xl font-black text-gray-900 tracking-tight">Space360</h1>
              <p className="text-xl font-bold text-gray-500 mt-1 uppercase tracking-widest">Progress Report</p>
            </div>
            <div className="text-right">
              <h2 className="text-2xl font-bold text-brand-700">{report.siteName}</h2>
              <p className="text-sm font-bold text-gray-500 mt-1.5 bg-gray-100 inline-block px-3 py-1 rounded-full">{report.dateRange}</p>
            </div>
          </div>

          <div className="mb-10 bg-gray-50 p-6 rounded-xl border border-gray-100 shadow-inner">
            <h3 className="text-lg font-bold text-gray-800 mb-4 uppercase tracking-wide">Overall Progress</h3>
            <ProgressBar value={report.overallProgress} label="Estimated Completion" colorClass="bg-brand-600" />
          </div>

          <div className="space-y-10">
            <h3 className="text-xl font-black text-gray-900 border-b-2 border-gray-100 pb-3 uppercase tracking-wide">Location Summaries</h3>
            {report.locations.map((loc: any, i: number) => (
              <div key={i} className="page-break-inside-avoid">
                <h4 className="text-lg font-bold text-gray-800 mb-4 flex items-center">
                  <span className="w-2 h-6 bg-brand-500 rounded-full mr-3"></span>
                  {loc.name}
                </h4>
                <div className="flex space-x-6 mb-5">
                  <div className="flex-1 relative">
                    <div className="absolute top-2 left-2 bg-black/70 text-white text-xs font-bold px-2 py-1 rounded shadow z-10 backdrop-blur-sm uppercase">Before</div>
                    <img src={loc.beforeThumb} alt="Before" className="w-full h-48 object-cover rounded-lg shadow-md border border-gray-200" />
                  </div>
                  <div className="flex-1 relative">
                    <div className="absolute top-2 left-2 bg-brand-600/90 text-white text-xs font-bold px-2 py-1 rounded shadow z-10 backdrop-blur-sm uppercase">After</div>
                    <img src={loc.afterThumb} alt="After" className="w-full h-48 object-cover rounded-lg shadow-md border border-brand-200" />
                  </div>
                </div>
                <div className="bg-brand-50 p-4 rounded-xl border border-brand-100 flex items-start shadow-sm">
                  <div className="p-2 bg-brand-100 rounded-lg mr-4">
                    <Sparkles className="w-5 h-5 text-brand-600" />
                  </div>
                  <div>
                    <h5 className="text-sm font-bold text-brand-900 mb-1 uppercase tracking-wide">AI Summary</h5>
                    <p className="text-brand-800 font-medium leading-relaxed">{loc.summary}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>

          <div className="mt-16 pt-8 border-t-2 border-gray-100 text-center text-sm text-gray-400 font-bold flex justify-between items-center">
            <span className="text-gray-500 tracking-wider">Space360 | SGB Dev Apps</span>
            <span className="bg-gray-100 px-3 py-1 rounded-full">Generated on {new Date().toLocaleDateString()}</span>
          </div>

          <div className="mt-10 flex justify-center print:hidden">
            <button onClick={exportPDF} className="btn-primary flex items-center px-8 py-3 rounded-full text-lg shadow-xl hover:-translate-y-1 transition-all">
              <Download className="w-5 h-5 mr-3" />
              Download as PDF
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default ReportsPage;
