"""add_project_metadata_to_site

Revision ID: 0c641b021c3f
Revises: 46884b7b0ded
Create Date: 2026-08-16 21:30:51.636368

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0c641b021c3f'
down_revision: Union[str, None] = '46884b7b0ded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('last_activity_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'last_activity_at')
    op.drop_column('sites', 'description')
    # ### end Alembic commands ###
