"""Add issue comments table

Revision ID: 27236b240f6d
Revises: ab091fb27000
Create Date: 2026-08-09 18:23:31.007731

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '27236b240f6d'
down_revision: Union[str, None] = 'ab091fb27000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('issue_id', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue_comments')
    # ### end Alembic commands ###
