"""add_inspection_paths

Revision ID: 3b034533580c
Revises: d7f0941fb270
Create Date: 2026-09-20 23:04:50.032826

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3b034533580c'
down_revision: Union[str, None] = 'd7f0941fb270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_videos_job_id'), table_name='videos')
    op.drop_index(op.f('idx_videos_site_id'), table_name='videos')
    op.drop_index(op.f('idx_videos_status'), table_name='videos')
    op.drop_index(op.f('idx_videos_user_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('idx_issue_assignments_contractor_id'), table_name='issue_assignments')
    op.drop_index(op.f('idx_issue_assignments_issue_id'), table_name='issue_assignments')
    op.drop_index(op.f('idx_comments_content_fts'), table_name='issue_comments', postgresql_using='gin')
    op.drop_index(op.f('idx_issue_comments_issue_id'), table_name='issue_comments')
    op.drop_index(op.f('idx_issues_created_at'), table_name='issues')
    op.drop_index(op.f('idx_issues_created_by'), table_name='issues')
    op.drop_index(op.f('idx_issues_description_fts'), table_name='issues', postgresql_using='gin')
    op.drop_index(op.f('idx_issues_location_id'), table_name='issues')
    op.drop_index(op.f('idx_issues_status'), table_name='issues')
    op.drop_index(op.f('idx_issues_title_fts'), table_name='issues', postgresql_using='gin')
    op.drop_index(op.f('idx_issues_type'), table_name='issues')
    op.alter_column('video_frames', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_video_frames_video_id'), table_name='video_frames')
    op.alter_column('video_uploads', 'file_size_bytes',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('video_uploads', 'upload_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('video_uploads', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('video_uploads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_video_uploads_path_id'), table_name='video_uploads')
    op.drop_index(op.f('idx_video_uploads_user_id'), table_name='video_uploads')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_video_uploads_user_id'), 'video_uploads', ['user_id'], unique=False)
    op.create_index(op.f('idx_video_uploads_path_id'), 'video_uploads', ['path_id'], unique=False)
    op.alter_column('video_uploads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('video_uploads', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('video_uploads', 'upload_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('video_uploads', 'file_size_bytes',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.create_index(op.f('idx_video_frames_video_id'), 'video_frames', ['video_id'], unique=False)
    op.alter_column('video_frames', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_issues_type'), 'issues', ['issue_type'], unique=False)
    op.create_index(op.f('idx_issues_title_fts'), 'issues', [sa.literal_column("to_tsvector('english'::regconfig, COALESCE(title, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_issues_status'), 'issues', ['status'], unique=False)
    op.create_index(op.f('idx_issues_location_id'), 'issues', ['location_id'], unique=False)
    op.create_index(op.f('idx_issues_description_fts'), 'issues', [sa.literal_column("to_tsvector('english'::regconfig, COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_issues_created_by'), 'issues', ['created_by'], unique=False)
    op.create_index(op.f('idx_issues_created_at'), 'issues', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_issue_comments_issue_id'), 'issue_comments', ['issue_id'], unique=False)
    op.create_index(op.f('idx_comments_content_fts'), 'issue_comments', [sa.literal_column("to_tsvector('english'::regconfig, COALESCE(comment_text, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_issue_assignments_issue_id'), 'issue_assignments', ['issue_id'], unique=False)
    op.create_index(op.f('idx_issue_assignments_contractor_id'), 'issue_assignments', ['contractor_id'], unique=False)
    op.create_table('videos',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('site_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'processing', 'stitching', 'completed', 'failed', name='videostatusenum'), autoincrement=False, nullable=True),
    sa.Column('gcs_mp4_uri', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gcs_metadata_uri', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('capture_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('videos_site_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('videos_pkey'))
    )
    op.create_index(op.f('idx_videos_user_id'), 'videos', ['user_id'], unique=False)
    op.create_index(op.f('idx_videos_status'), 'videos', ['status'], unique=False)
    op.create_index(op.f('idx_videos_site_id'), 'videos', ['site_id'], unique=False)
    op.create_index(op.f('idx_videos_job_id'), 'videos', ['job_id'], unique=False)
    # ### end Alembic commands ###
