"""add_contractor_site_assignments

Revision ID: 46884b7b0ded
Revises: 828cd1d88d52
Create Date: 2026-08-16 21:10:54.280295

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '46884b7b0ded'
down_revision: Union[str, None] = '828cd1d88d52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
