"""Add pending and critical issue statuses

Revision ID: 5f125a469127
Revises: 27236b240f6d
Create Date: 2026-08-09 18:47:47.906439

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '5f125a469127'
down_revision: Union[str, None] = '27236b240f6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
