"""Add issue_photos table

Revision ID: 67c80c35f6b3
Revises: 87dd4a31a79f
Create Date: 2026-08-15 10:17:28.877707

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '67c80c35f6b3'
down_revision: Union[str, None] = '87dd4a31a79f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
