"""add_video_sequence_capture

Revision ID: 7900d6512df1
Revises: 0c641b021c3f
Create Date: 2026-08-16 22:09:07.813311

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7900d6512df1'
down_revision: Union[str, None] = '0c641b021c3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capture_sessions', sa.Column('video_url', sa.String(), nullable=True))
    op.add_column('capture_sessions', sa.Column('fps', sa.Integer(), nullable=True))
    op.add_column('capture_sessions', sa.Column('total_frames', sa.Integer(), nullable=True))
    op.add_column('capture_sessions', sa.Column('processing_status', sa.String(), nullable=True))
    op.add_column('capture_sessions', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('capture_sessions', sa.Column('processing_completed_at', sa.DateTime(), nullable=True))
    op.add_column('issues', sa.Column('frame_a_id', sa.String(), nullable=True))
    op.add_column('issues', sa.Column('frame_b_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'issues', 'capture_frames', ['frame_b_id'], ['id'])
    op.create_foreign_key(None, 'issues', 'capture_frames', ['frame_a_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_column('issues', 'frame_b_id')
    op.drop_column('issues', 'frame_a_id')
    op.drop_column('capture_sessions', 'processing_completed_at')
    op.drop_column('capture_sessions', 'error_message')
    op.drop_column('capture_sessions', 'processing_status')
    op.drop_column('capture_sessions', 'total_frames')
    op.drop_column('capture_sessions', 'fps')
    op.drop_column('capture_sessions', 'video_url')
    # ### end Alembic commands ###
