"""Add pending and critical issue statuses

Revision ID: 79541c5c3399
Revises: 5f125a469127
Create Date: 2026-08-09 19:11:22.080203

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '79541c5c3399'
down_revision: Union[str, None] = '5f125a469127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
