"""Add issue_notifications table

Revision ID: 828cd1d88d52
Revises: 67c80c35f6b3
Create Date: 2026-08-16 19:42:41.773209

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '828cd1d88d52'
down_revision: Union[str, None] = '67c80c35f6b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('issue_id', sa.String(), nullable=False),
    sa.Column('sent_to', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue_notifications')
    # ### end Alembic commands ###
