"""Add issue type classification

Revision ID: 87dd4a31a79f
Revises: 79541c5c3399
Create Date: 2026-08-14 23:23:17.070565

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '87dd4a31a79f'
down_revision: Union[str, None] = '79541c5c3399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    issue_type_enum = sa.Enum('defect', 'safety_issue', 'quality_issue', 'incomplete_work', 'rework_required', name='issuetypeenum')
    issue_type_enum.create(op.get_bind())
    op.add_column('issues', sa.Column('issue_type', issue_type_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'issue_type')
    sa.Enum('defect', 'safety_issue', 'quality_issue', 'incomplete_work', 'rework_required', name='issuetypeenum').drop(op.get_bind())
    # ### end Alembic commands ###
