"""Add contractors and issues

Revision ID: ab091fb27000
Revises: fac1cb36615b
Create Date: 2026-08-09 14:23:50.493807

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ab091fb27000'
down_revision: Union[str, None] = 'fac1cb36615b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('trade', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('access_level', sa.Enum('view_only', 'comment_and_change_status', 'create_issue', 'close_and_review', name='accesslevelenum'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issues',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_review', 'pending', 'closed', name='issuestatusenum'), nullable=True),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('session_a_id', sa.String(), nullable=True),
    sa.Column('session_b_id', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location_points.id'], ),
    sa.ForeignKeyConstraint(['session_a_id'], ['capture_sessions.id'], ),
    sa.ForeignKeyConstraint(['session_b_id'], ['capture_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issue_assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('issue_id', sa.String(), nullable=False),
    sa.Column('contractor_id', sa.String(), nullable=False),
    sa.Column('assigned_by', sa.String(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue_assignments')
    op.drop_table('issues')
    op.drop_table('contractors')
    # ### end Alembic commands ###
