"""add frame gps correlations and path metadata

Revision ID: d7f0941fb270
Revises: 15dff193519b
Create Date: 2026-09-06 17:10:04.195599

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd7f0941fb270'
down_revision: Union[str, None] = '15dff193519b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frame_gps_correlations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('path_id', sa.String(), nullable=False),
    sa.Column('waypoint_id', sa.String(), nullable=False),
    sa.Column('frame_id', sa.String(), nullable=False),
    sa.Column('timestamp_offset_ms', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['frame_id'], ['video_frames.id'], ),
    sa.ForeignKeyConstraint(['path_id'], ['paths.id'], ),
    sa.ForeignKeyConstraint(['waypoint_id'], ['path_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('paths', sa.Column('pathStartTimestampNanos', sa.BigInteger(), nullable=True))
    op.add_column('paths', sa.Column('cameraStartTimestampNanos', sa.BigInteger(), nullable=True))
    op.add_column('paths', sa.Column('clockOffsetNanos', sa.BigInteger(), nullable=True))
    op.add_column('paths', sa.Column('recordingSessionJson', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_video_uploads_user_id'), 'video_uploads', ['user_id'], unique=False)
    op.create_index(op.f('idx_video_uploads_path_id'), 'video_uploads', ['path_id'], unique=False)
    op.alter_column('video_uploads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('video_uploads', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('video_uploads', 'upload_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('video_uploads', 'file_size_bytes',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.create_index(op.f('idx_video_frames_video_id'), 'video_frames', ['video_id'], unique=False)
    op.alter_column('video_frames', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('paths', 'recordingSessionJson')
    op.drop_column('paths', 'clockOffsetNanos')
    op.drop_column('paths', 'cameraStartTimestampNanos')
    op.drop_column('paths', 'pathStartTimestampNanos')
    op.create_index(op.f('idx_issues_type'), 'issues', ['issue_type'], unique=False)
    op.create_index(op.f('idx_issues_title_fts'), 'issues', [sa.literal_column("to_tsvector('english'::regconfig, COALESCE(title, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_issues_status'), 'issues', ['status'], unique=False)
    op.create_index(op.f('idx_issues_location_id'), 'issues', ['location_id'], unique=False)
    op.create_index(op.f('idx_issues_description_fts'), 'issues', [sa.literal_column("to_tsvector('english'::regconfig, COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_issues_created_by'), 'issues', ['created_by'], unique=False)
    op.create_index(op.f('idx_issues_created_at'), 'issues', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_issue_comments_issue_id'), 'issue_comments', ['issue_id'], unique=False)
    op.create_index(op.f('idx_comments_content_fts'), 'issue_comments', [sa.literal_column("to_tsvector('english'::regconfig, COALESCE(comment_text, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_issue_assignments_issue_id'), 'issue_assignments', ['issue_id'], unique=False)
    op.create_index(op.f('idx_issue_assignments_contractor_id'), 'issue_assignments', ['contractor_id'], unique=False)
    op.drop_table('frame_gps_correlations')
    # ### end Alembic commands ###
