"""add_inspection_paths_again

Revision ID: eca5f088d8d1
Revises: 3b034533580c
Create Date: 2026-09-20 23:46:33.037593

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'eca5f088d8d1'
down_revision: Union[str, None] = '3b034533580c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspection_path_points', sa.Column('timestamp_seconds', sa.Float(), nullable=True))
    op.alter_column('inspection_paths', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('path_points', sa.Column('timestamp_seconds', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('path_points', 'timestamp_seconds')
    op.alter_column('inspection_paths', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('inspection_path_points', 'timestamp_seconds')
    # ### end Alembic commands ###
